---
name: CI
on:
  pull_request: ~
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    permissions:
      contents: read
      packages: read
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ["nightly"]

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: nvim-neorocks/nvim-busted-action@v1
        with:
          nvim_version: ${{ matrix.neovim_version }}
