---
name: "Release"
on:
  push:
    tags:
      - "v*.*.*"

permissions: {}

jobs:
  luarocks-release:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    name: Luarocks Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: env.LUAROCKS_API_KEY != null
      - name: Luarocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        if: env.LUAROCKS_API_KEY != null
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
